### PR TITLE
restructure

### PR DESCRIPTION
**Pull request by ghost**
Sorry for the huge pull request, I know there are a lot of changes here.  Let me walk you through them:
- MIT license
  - your code didn't have an explicit license, so I tagged it as MIT even though I am not the copyright holder
  - please don't sue me
- use npm for dependencies instead of bundling them manually
  - requires node, I recommend you install that with nvm (node version manager) if possible
  - just run `npm install` and all the dependencies will be downloaded into `node_modules`
- use gulp
  - gulp is a task runner
  - you can either `npm install gulp-cli -g` and run `gulp`, or you can use an npm script, `npm run build`
  - there are tasks for
    - `gulp lint` - check JavaScript for potential problems
      - uses eslint, check the .eslint.conf.json file for rules
    - `gulp build` - bundle third-party dependencies and configuration into `lib` folder
      - may add a "babel" transpiler step at a later date
    - `gulp clean` - delete build artifacts
    - `gulp watch` - watch files for changes and rebuild as necessary
    - `gulp webserver` - start a local web server and browser which reloads automatically as changes are made (implies watch)
    - `gulp deploy` - clones built code to `gh-pages` branch and pushes to `origin` remote
- use SystemJS
   - SystemJS is a highly configurable JavaScript module system, that allows you to import and export modules from JS files
   - it supports globals, AMD, CommonJS, and UMD - all different competing module standards
   - configuration is in `system.config.js`
- changed code to use CommonJS
   - nothing is in global scope
   - locally declared variables do not actually leak into global scope
- use ghooks
   - hooks into git so that when you pull, an `npm install` is run automatically (after the first one, because ghooks has to be installed this way)
   - runs lint task when commits are run
- use core-js
  - polyfill library

Note this did require me to restructure the project a bit.
  - js files were moved into `js` folder, so SystemJS could be configured to treat it as a package

Love the app, and your YouTube channel.  If you want any help or even web dev tutoring, let me know!

Thanks,
\- Joe

### CODE REVIEW

**Comment by michaelnew** [comment]
Hey this is really great, thank you so much. Considering I published the YT video on this earlier today you must work fast :)

So this is obviously a huge change, although on the whole I think everything makes sense and looks good. I'm going to spend some time playing around and making sure I understand everything before merging, and I may end up cherry picking things into different commits rather than merging everything at once. More for my own understanding than anything else.

Thanks again man. This is fantastic.

**Comment by ghost** [comment]
No problem.  If you want to talk about the changes, have any questions, or really anything else, you can talk to me on Google; same screen name as here @gmail.com.

**Comment by matthewhubblerose** [comment]
Is MIDI.js published to npm? I can't find it using the search, but it does have a package.json:
https://github.com/mudcube/MIDI.js/blob/master/package.json

I'm not too up on JS development, but to me it looks like it could be published to npm pretty easily (just `npm publish`) - it would mean it could be pulled into this repo through npm rather than having the current git sub-module which would be nice. Presumably the MIDI.js author would need to publish it on npm.

**Comment by ghost** [comment]
@matthewhubblerose It is, but I ran into two issues trying to use it:
1. If you `npm install midi`, it tries to do a build, which requires a compiler to be installed
2. The `.gitignore` file ignores the `build` directory, so if I manage to skip 1, I have no compiled file (when installing from `npm`)

Overall, I found it easier just to have the gulpfile read from the submodule directory.

**Comment by matthewhubblerose** [comment]
@errorx666 Hmm, so there is a package named "midi" in npm, but I don't think it's the MIDI.js code:
```
$ npm owner ls midi
justinlatimer <justin@doublemu.com>
drewish <drewish@katherinehouse.com>
tmpvar <tmpvar@gmail.com>
```

It appears to be this repo:
https://github.com/justinlatimer/node-midi

Explains why a compiler was required, as it's a C++ repo. MIDI.js looks like pure JS, so we'd need to get a pull request accepted in MIDI.js changing the package.json name from "midi" to something unique, so it could then be depended on. Sounds like hassle though, and that repo doesn't look too active.

**Comment by ghost** [comment]
@matthewhubblerose It is possible to `npm install` straight from a Github repository, but I ran into the same problems doing that.

**Pull request merged**
